name: Bugreport
description: You can report a vanilla bug or issue here.  Before starting, it is worth searching to see if your issue has already been reported. Search both Open *and* Closed issues. If it's in Closed issues, maybe it is already resolved or resolvable.
Especially with crashes, unique words or code from the first couple of lines can be fruitful to search for: a good one to search is the last word before (.
labels: ["status: new"]

body:
  - type: input
    id: shortdescription
    attributes:
      label: Game Version
      description: What Game Version were you using?
      placeholder: v1.20.
    validations:
      required: false
  - type: dropdown
    id: operating-systems
    attributes:
      label: Platform
      description: Select your operating system.
      options:
        - Windows
        - Mac
        - Linux
    validations:
      required: false
  - type: dropdown
    id: modded
    attributes:
      label: Modded
      description: Did you use mods?
      options:
        - Modded
        - Vanilla
    validations:
      required: false
  - type: dropdown
    id: playmode
    attributes:
      label: SP/MP
      description: Single- or Multi-player?
      options:
        - Singleplayer
        - Multiplayer
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Explain the issue you're running into.
      placeholder: Explain it here.
    validations:
      required: false
  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce
      description: Explain how we could reproduce your bug/issue.
      placeholder: 1. Make a '....' 2. Use it on '....' 3. It crashes / doesn't do the thing.
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Attach a screenshot if it helps explain the issue / shows a visual bug.
      placeholder: Drag and drop pictures here.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Logs (Required)
      description: In the game's `Logs` folder there will be useful information in almost all cases.  For the gameplay session when the issue occurred, please drag and drop **all** those log files here. Please provide both server- and client- logs - or in Multiplayer, you will only have access to client- logs if you're the player reporting the issue.  If you're the server owner, post server- logs and if relevant please try to obtain the client logs from the affected player as well.<br><br>If you re-started the game already after the issue occurred, your older logs are in folder `Logs\Archive`.<br><br>In the event of a crash please also copy & paste the information from the Crash Reporter screen, paste it between the triple quote marks in the box below. This helps us quickly find the issue, and may help other players with the same issue.
      placeholder: Paste crash between the triple backticks. Also drag and drop full log files here - especially `client-main.log`
      value: "Log files are now required in all cases (unless it's a website issue)
      
      You can also cut and paste from any crash report here:
      ```Crash```"
    validations:
      required: true
